version: '2'

services:

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=wordpress_db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=blabla
      - WORDPRESS_DB_NAME=wordpress
    links:
      - wordpress_db:wordpress_db

  wordpress_db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3307:3306
#volumes:
#  - /doc/wordpress_db:/var/lib/mysql
volumes:
  db_data: {}
  wordpress_data: {}